name: update repo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: fetch packages
      run: |
        declare -A l
        source packages
        for p in "${!l[@]}"; do
          curl -sLO "${l[$p]}"
          if [[ -f PKGBUILD ]]; then
            makepkg -sf
            rm PKGBUILD
          fi
        done

    - name: update
      run: |
        cat << EOF > entrypoint.sh
        cd /build
        mkdir repo
        repo-add repo/lennypeers.db.tar.gz *.pkg.tar.zst
        # well, got issues uploading symlinks...
        rm repo/lennypeers.{db,files}
        mv repo/lennypeers.db{.tar.gz,}
        mv repo/lennypeers.files{.tar.gz,}
        mv *.pkg.tar.zst repo
        EOF
        docker run -t -v $PWD:/build archlinux /bin/bash /build/entrypoint.sh

    - name: delete previous release
      uses: actions/github-script@v4
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { owner, repo } = context.repo
          const { data: { id } } = await github.repos.getLatestRelease({ owner, repo })
          await github.repos.deleteRelease({ owner, repo, release_id: id })

    - name: create tag
      id: create_tag
      run: |
        # same tag because we need a static server name
        # either way pacman won't be abble to find the server
        tag_name=repo
        echo "::set-output name=tag::$tag_name"
        echo $tag_name

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ github.workspace }}/repo/*
        tag_name: ${{ steps.create_tag.outputs.tag }}
        draft: false
        body: lennypeers' packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
