name: update repo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: fetch/build packages
      run: |
        cat << EOF > entrypoint.sh
        cd /build
        useradd builduser -m
        passwd -d builduser
        pacman -Syu --noconfirm --needed sudo base-devel
        echo -e 'builduser ALL=(ALL) ALL\n' >> /etc/sudoers
        chown -R builduser:builduser ./
        sudo -u builduser bash -c 'makepkg -si --noconfirm'
        EOF

        # download packages and build if needed
        declare -a l
        source packages
        for p in "${l[@]}"; do
          curl -sLO "$p"
          if [[ $p == file://* ]]; then
            docker run -t -v $PWD:/build archlinux /bin/bash /build/entrypoint.sh
          fi
        done

    - name: create repo
      run: |
        cat << EOF > entrypoint.sh
        cd /build
        mkdir repo
        repo-add repo/lennypeers.db.tar.gz *.pkg.tar.*
        # well, got issues uploading symlinks...
        rm repo/lennypeers.{db,files}
        mv repo/lennypeers.db{.tar.gz,}
        mv repo/lennypeers.files{.tar.gz,}
        mv *.pkg.tar.* repo
        EOF
        docker run -t -v $PWD:/build archlinux /bin/bash /build/entrypoint.sh

    - name: delete previous release
      uses: actions/github-script@v4
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { owner, repo } = context.repo
          const { data: { id } } = await github.repos.getLatestRelease({ owner, repo })
          await github.repos.deleteRelease({ owner, repo, release_id: id })

    - name: create tag
      id: create_tag
      run: |
        # same tag because we need a static server name
        # either way pacman won't be able to find the server
        tag_name=repo
        echo "::set-output name=tag::$tag_name"
        echo $tag_name

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ github.workspace }}/repo/*
        tag_name: ${{ steps.create_tag.outputs.tag }}
        draft: false
        body: lennypeers' packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
